import React from 'react';
import {AbsoluteFill, Audio, Composition, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';

const C={bg:'#070912',panel:'#0e1422',line:'#26314a',text:'#f4f7ff',muted:'#93a0bb',accent:'#63e6ff',purple:'#9b7cff',green:'#65e6a8',red:'#ff6b7a'};
const scenes=[
{id:'HOOK',start:0,dur:35,title:'WHAT REALLY HAPPENS WHEN YOU TYPE A URL?',kicker:'THE HIDDEN JOURNEY OF A WEB REQUEST'},
{id:'BROWSER',start:35,dur:40,title:'STEP 1 — THE BROWSER',kicker:'URL → DESTINATION'},
{id:'DNS',start:75,dur:50,title:'STEP 2 — DNS',kicker:'DOMAIN NAME → IP ADDRESS'},
{id:'ROUTE',start:125,dur:50,title:'STEP 3 — THE NETWORK ROUTE',kicker:'PHONE → ROUTER → ISP → INTERNET'},
{id:'TCP',start:175,dur:50,title:'STEP 4 — TCP HANDSHAKE',kicker:'SYN → SYN-ACK → ACK'},
{id:'TLS',start:225,dur:60,title:'STEP 5 — HTTPS / TLS',kicker:'IDENTITY + ENCRYPTION'},
{id:'HTTP',start:285,dur:50,title:'STEP 6 — HTTP REQUEST',kicker:'THE BROWSER ASKS FOR THE PAGE'},
{id:'SERVER',start:335,dur:60,title:'STEP 7 — SERVER INFRASTRUCTURE',kicker:'LOAD BALANCER → APP → DATA'},
{id:'RESPONSE',start:395,dur:40,title:'STEP 8 — THE RESPONSE',kicker:'200 OK'},
{id:'RENDER',start:435,dur:60,title:'STEP 9 — THE BROWSER RENDERS',kicker:'HTML → DOM → CSS → PAINT'},
{id:'FAST',start:495,dur:45,title:'STEP 10 — WHY IT FEELS FAST',kicker:'CACHE • CDN • COMPRESSION • HTTP/2 • HTTP/3'},
{id:'SECURITY',start:540,dur:35,title:'THE SECURITY ANGLE',kicker:'TRUST THE DOMAIN — NOT THE LOOK'},
{id:'FINAL',start:575,dur:25,title:'ONE URL. A WHOLE JOURNEY.',kicker:'THE INTERNET IS FAR MORE COMPLEX THAN IT LOOKS.'}];
const sec=(s:number)=>s*30;

function Grid(){return <AbsoluteFill style={{backgroundImage:`linear-gradient(${C.line}33 1px,transparent 1px),linear-gradient(90deg,${C.line}33 1px,transparent 1px)`,backgroundSize:'80px 80px',opacity:.22}}/>}
function Header({scene}:{scene:any}){return <div style={{position:'absolute',top:48,left:64,right:64,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:22,fontWeight:800,color:C.accent}}>TECH<span style={{color:C.text}}>ORBIT</span></div><div style={{fontSize:16,color:C.muted,letterSpacing:2}}>{scene.kicker}</div></div>}
function Title({children,size=62}:{children:React.ReactNode,size?:number}){const f=useCurrentFrame();const o=interpolate(f,[0,18,36],[0,1,1],{extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});return <div style={{opacity:o,fontSize:size,color:C.text,fontWeight:850,letterSpacing:-1.5,lineHeight:1.05}}>{children}</div>}
function Footer({scene}:{scene:any}){const f=useCurrentFrame();const p=Math.min(1,f/(scene.dur*30));return <div style={{position:'absolute',left:64,right:64,bottom:34,display:'flex',alignItems:'center',gap:18}}><div style={{height:3,flex:1,background:C.line}}><div style={{height:'100%',width:'100%',background:C.accent,transformOrigin:'left',transform:`scaleX(${p})`}}/></div><div style={{fontSize:14,color:C.muted}}>{scene.id}</div></div>}
function Box({children,style={}}:{children:React.ReactNode,style?:React.CSSProperties}){return <div style={{border:`1px solid ${C.line}`,background:C.panel,borderRadius:18,padding:28,...style}}>{children}</div>}
function Packet({x1,y1,x2,y2,delay=0}:{x1:number,y1:number,x2:number,y2:number,delay?:number}){const f=useCurrentFrame();const t=((f-delay)%75+75)%75/75;return <div style={{position:'absolute',left:x1+(x2-x1)*t-5,top:y1+(y2-y1)*t-5,width:10,height:10,borderRadius:50,background:C.accent,boxShadow:`0 0 20px ${C.accent}`}}/>}
function Route(){const nodes=[['PHONE',110],['ROUTER',360],['ISP',610],['INTERNET',860],['SERVER',1110]];return <div style={{position:'absolute',left:0,right:0,top:390,height:180}}>{nodes.map(([label,x],i)=><React.Fragment key={String(label)}><Box style={{position:'absolute',left:Number(x),top:40,width:190,height:70,padding:0,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,color:i===4?C.green:C.text}}>{label}</Box>{i<4&&<div style={{position:'absolute',left:Number(x)+190,top:74,width:60,height:3,background:C.line}}/>}</React.Fragment>)}<Packet x1={300} y1={464} x2={360} y2={464}/><Packet x1={550} y1={464} x2={610} y2={464} delay={18}/><Packet x1={800} y1={464} x2={860} y2={464} delay={36}/><Packet x1={1050} y1={464} x2={1110} y2={464} delay={54}/></div>}
function Scene({scene}:{scene:any}){const id=scene.id;return <AbsoluteFill style={{background:C.bg,color:C.text,fontFamily:'Inter,Arial,sans-serif',overflow:'hidden'}}><Grid/><Header scene={scene}/><div style={{position:'absolute',left:64,top:155,right:64}}><div style={{fontSize:18,color:C.accent,fontWeight:800,letterSpacing:2,marginBottom:18}}>{id==='HOOK'?'THE INTERNET, ONE REQUEST AT A TIME':scene.kicker}</div><Title size={id==='HOOK'?76:62}>{scene.title}</Title></div>
{id==='HOOK'&&<><div style={{position:'absolute',left:110,top:360,fontSize:82,fontWeight:800}}>youtube.com<span style={{color:C.accent}}>|</span></div><Box style={{position:'absolute',right:110,top:350,width:360,height:220}}><div style={{color:C.muted,fontSize:14}}>REQUEST TRACE</div>{['DNS','TCP/TLS','HTTP','SERVER','RESPONSE'].map((x,i)=><div key={x} style={{display:'flex',justifyContent:'space-between',marginTop:17,color:i<4?C.text:C.green}}><span>{x}</span><span>{i<4?'→':'✓'}</span></div>)}</Box></>}
{id==='BROWSER'&&<Box style={{position:'absolute',left:150,top:355,right:150,height:250}}><div style={{color:C.muted,fontSize:14,marginBottom:22}}>ADDRESS BAR</div><div style={{fontSize:44,fontWeight:700}}>https://<span style={{color:C.accent}}>example.com</span></div><div style={{marginTop:34,display:'flex',gap:18}}><span style={{padding:'10px 16px',borderRadius:10,background:'#182238',color:C.muted}}>https://</span><span style={{padding:'10px 16px',borderRadius:10,background:'#112c35',color:C.accent}}>example.com</span></div></Box>}
{id==='DNS'&&<div style={{position:'absolute',left:170,top:330,right:170,display:'flex',flexDirection:'column',gap:9,alignItems:'center'}}>{['example.com','DNS Resolver','Root .','TLD .com','Authoritative DNS','93.184.216.34'].map((x,i)=><React.Fragment key={x}><div style={{padding:'12px 28px',borderRadius:14,border:`1px solid ${i===5?C.green:C.line}`,background:C.panel,color:i===5?C.green:C.text,fontWeight:700}}>{x}</div>{i<5&&<div style={{color:C.accent}}>↓</div>}</React.Fragment>)}</div>}
{id==='ROUTE'&&<Route/>}
{id==='TCP'&&<div style={{position:'absolute',left:250,top:365,right:250,display:'flex',justifyContent:'space-between',alignItems:'center'}}><Box style={{width:240,height:150,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,fontSize:28}}>PHONE</Box><div style={{position:'absolute',left:280,right:280,top:5}}>{['SYN','SYN-ACK','ACK'].map((x,i)=><div key={x} style={{marginBottom:18,textAlign:i===1?'right':'left',color:i===1?C.green:C.accent,fontSize:26,fontWeight:800}}>{x}</div>)}</div><Box style={{width:240,height:150,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,fontSize:28}}>SERVER</Box></div>}
{id==='TLS'&&<div style={{position:'absolute',left:190,top:350,right:190,display:'flex',gap:40,alignItems:'center'}}><Box style={{flex:1,color:C.red,fontSize:28}}>password=123456</Box><div style={{fontSize:50,color:C.accent}}>→</div><Box style={{flex:1,color:C.green,fontSize:23,wordBreak:'break-all'}}>8fA9•k2X•Qp7•mZ4•Lx8</Box><div style={{position:'absolute',left:'42%',top:210,fontSize:24,color:C.green,fontWeight:800}}>🔒 ENCRYPTED CONNECTION</div></div>}
{id==='HTTP'&&<Box style={{position:'absolute',left:180,top:350,right:180,fontFamily:'monospace',fontSize:28,lineHeight:1.7}}><div style={{color:C.accent}}>GET /</div><div>Host: example.com</div><div>Accept: text/html</div><div style={{color:C.muted}}>Cookie: session=…</div></Box>}
{id==='SERVER'&&<div style={{position:'absolute',left:100,top:345,right:100,display:'flex',alignItems:'center',justifyContent:'space-between'}}>{['REQUEST','LOAD BALANCER','APP SERVER','CACHE / DB','RESPONSE'].map((x,i)=><React.Fragment key={x}><Box style={{width:170,height:130,padding:10,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',fontWeight:800,color:i===2?C.accent:C.text}}>{x}</Box>{i<4&&<div style={{color:C.accent,fontSize:30}}>→</div>}</React.Fragment>)}</div>}
{id==='RESPONSE'&&<div style={{position:'absolute',left:220,top:365,right:220,display:'flex',alignItems:'center',gap:45}}><div style={{fontSize:110,fontWeight:900,color:C.green}}>200</div><div><div style={{fontSize:34,fontWeight:800}}>OK</div><div style={{color:C.muted,fontSize:20,marginTop:10}}>HTML • CSS • JS • IMAGES • FONTS</div></div></div>}
{id==='RENDER'&&<div style={{position:'absolute',left:140,top:350,right:140,display:'flex',gap:18,alignItems:'center'}}>{['HTML','DOM','CSS','LAYOUT','PAINT','WEBPAGE'].map((x,i)=><React.Fragment key={x}><Box style={{width:140,height:120,padding:0,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,color:i===5?C.green:C.text}}>{x}</Box>{i<5&&<div style={{color:C.accent}}>→</div>}</React.Fragment>)}</div>}
{id==='FAST'&&<div style={{position:'absolute',left:150,top:360,right:150,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:16}}>{['CACHE','CDN','COMPRESS','HTTP/2','HTTP/3'].map((x,i)=><Box key={x} style={{height:150,padding:0,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,color:i===1?C.accent:C.text}}>{x}</Box>)}</div>}
{id==='SECURITY'&&<div style={{position:'absolute',left:180,top:360,right:180,display:'flex',alignItems:'center',justifyContent:'space-between'}}><Box style={{fontSize:28}}>example.com</Box><div style={{fontSize:45,color:C.green}}>✓</div><Box style={{fontSize:28,color:C.red}}>examp1e.com</Box><div style={{fontSize:45,color:C.red}}>✕</div></div>}
{id==='FINAL'&&<div style={{position:'absolute',left:110,right:110,top:350,display:'flex',flexWrap:'wrap',justifyContent:'center',gap:14}}>{['URL','DNS','IP','TCP/TLS','HTTP','SERVER','RESPONSE','BROWSER','WEBPAGE'].map((x,i)=><div key={x} style={{padding:'18px 24px',borderRadius:15,border:`1px solid ${i===8?C.green:C.line}`,background:C.panel,fontWeight:800,color:i===8?C.green:C.text}}>{x}{i<8&&<span style={{color:C.accent,marginLeft:18}}>→</span>}</div>)}</div>}
<Footer scene={scene}/></AbsoluteFill>}
function UrlJourney(){return <AbsoluteFill><Audio src={staticFile('voiceover.mp3')} volume={1}/><Audio src={staticFile('bg.mp3')} volume={0.055}/>{scenes.map(s=><Sequence key={s.id} from={sec(s.start)} durationInFrames={sec(s.dur)}><Scene scene={s}/></Sequence>)}</AbsoluteFill>}
export const RemotionRoot=()=> <Composition id="UrlJourney" component={UrlJourney} durationInFrames={600*30} fps={30} width={1920} height={1080}/>;
